version: '2'

services:
 launch:
  image: nginx:latest
  container_name: nginx_nodejs
  volumes:
    - $PWD/nginx.conf:/etc/nginx/site-available/default
  ports:
    - "80:80"
  external_links:
    - nodejs_app:nodejsapp
  restart: always